spring.application.name=concurrent-content-service

spring.datasource.url=jdbc:postgresql://localhost:5433/coffee_forum
spring.datasource.username=coffee_admin
spring.datasource.password=localdevpassword

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true